import Link from 'next/link'
import Head from 'next/head'

import { Button as MantineButton } from '@mantine/core'

import type { NextPage } from 'next'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Trello</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="text-lg text-blue-600">Trello風アプリケーション</h1>
        ああ
        <Link href="/hello" passHref>
          <MantineButton component="a">Next link button</MantineButton>
        </Link>
        <MantineButton className="mt-4 block">Click me!</MantineButton>
      </div>
    </>
  )
}

export default Home
