import Link from 'next/link'
import Head from 'next/head'

import { CustomButton } from '../components/uiParts'

import type { NextPage } from 'next'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Trello</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="text-lg text-blue-600">Trello風アプリケーション</h1>
        ああ
        <Link href="/hello" passHref>
          <CustomButton dent component="a">凹むボタン</CustomButton>
        </Link>

        <CustomButton className="mt-4 block">凹まないボタン</CustomButton>
      </div>
    </>
  )
}

export default Home
